# Generated by Django 5.1.15 on 2026-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre comercial del proveedor (ej: Stripe, PayPal).', max_length=100, verbose_name='Nombre')),
                ('code', models.SlugField(help_text='Identificador único en formato slug (ej: stripe).', unique=True, verbose_name='Código')),
                ('api_key', models.CharField(help_text='Clave de API proporcionada por el proveedor.', max_length=255, verbose_name='Clave de API')),
                ('environment', models.CharField(choices=[('sandbox', 'Pruebas (sandbox)'), ('production', 'Producción')], default='sandbox', max_length=20, verbose_name='Entorno')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el proveedor está disponible para procesar pagos.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
