# Generated by Django 5.1.15 on 2026-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='api_key',
            field=models.CharField(blank=True, help_text='Clave de API proporcionada por el proveedor. Si se deja vacía, se usará la del entorno (STRIPE_API_KEY).', max_length=255, verbose_name='Clave de API'),
        ),
    ]
