# Generated by Django 5.1.15 on 2026-05-15 10:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la transacción.', unique=True, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Importe de la transacción (debe ser positivo).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('currency', models.CharField(help_text='Código ISO 4217 (EUR, USD, GBP...).', max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe ser un código ISO 4217 de 3 letras en mayúsculas (ej: EUR, USD).', regex='^[A-Z]{3}$')], verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('refunded', 'Devuelta')], default='pending', max_length=20, verbose_name='Estado')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='providers.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('unpaid', 'Impago'), ('connection_error', 'Error de conexión'), ('refund', 'Devolución'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de incidencia')),
                ('description', models.TextField(help_text='Detalle de la incidencia detectada.', verbose_name='Descripción')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='transactions.transaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider', 'status'], name='transaction_provide_c57932_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='transaction_created_300c15_idx'),
        ),
    ]
