# Generated by Django 5.1.15 on 2026-05-21 11:07

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador asignado por la pasarela (PaymentIntent, etc.).', max_length=255, verbose_name='ID externo'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Último payload recibido de la pasarela.', verbose_name='Respuesta de la pasarela'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe ser un código ISO 4217 de 3 letras en mayúsculas (ej: EUR, USD).', regex='^[A-Z]{3}$')], verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único interno de la transacción.', unique=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada'), ('refunded', 'Devuelta')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
