# Generated by Django 5.1.15 on 2026-05-20 11:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Mínimo 0.50 (límite de Stripe).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))], verbose_name='Importe')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Stripe Session ID')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, verbose_name='Stripe PaymentIntent ID')),
                ('checkout_url', models.URLField(blank=True, help_text='URL de Stripe Checkout a la que se redirige al cliente.', max_length=1000, verbose_name='URL de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='providers.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
